language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: "9.6" # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - npm run build-client
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: fsa-pairexercise-deployment
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: c32ullv3QLRwq4S/OvvMiBGdO4/gb5cm0YBml77Xzf5y2atrymYBJFv001nrtip2VwnmBzGXjz18rgDCJQO4wb/NNY5gnbP5JjiR+TFDD1wAh2tazT9+68jFJEwnpcwMHSucZNqmkzEVtCyp9lPfEW59M5AoJdVDlB978AFoMMWlaZ7cxayeis6/IhTikQmZeW7qCoNmJ4cCN4x0YW00pqTXSaXiQS1U1n6aOphhCEP3s4Bo5fNgYig2C/g3GryaMXi2rwer5AFHf9FoHMl17FyCx/OWo3b9anvPktS+jkAMp79e1rv6GzDypLhh/wWNNpZUItTWHvWyG0KJ8DX0qGEp1tuQVDYm1BUDeaKYJUCfKHcFRhlB94wH6N9y3PYQeEtfX+yT+LeZ4u0GbzkvXxjXIcsiq5IqFRPiFn3ok2eX68auN5k26YyImJ/rCMGI6K8Ya2nhGGErlWIPpOxj4zEFA73S1pZiHrPmVfYdK4W7F0drAF8mUy6N3GcrPk9+t3T1fOsxfa9xvWpWaUH+gwH1gP795vfIZLDzXuTOWIsaj7HkLYFOBTx+7zrJhsGgS8e6IaQhNvqWVwp3tLLas6v5Qok9N8lEj0clujVJxgygO8jmyvAsV8bzWbHASrbq+00zUYt9Ah9J1pFmuMH6hYIIjkzgtQ4XYtt45y4aEDU=
